version: "3.8"

services:
  api:
    image: bnb:latest
    container_name: api
    working_dir: '/app'
    volumes:
        - ./:/app
    ports:
        - 5000:5000
        - 5001:5001
    entrypoint:
        - bash
    stdin_open: true

